### PR TITLE
Compatibility with NuttX-11

### PR DESCRIPTION
**Pull request by robertobucher**
The file src/filesystem.c is not compatible with NuttX 11, because of the redefinition of the type "DIR"

src/filesystem.c contains a check of __INCLUDE_DIRENT_H  now

The redefinition of the type "DIR" causes a failure of the compilation of the libmicroros.a.

### CODE REVIEW

**Comment by pablogs9** [comment]
Hello, @robertobucher have you considered including this in the mainline repo of rcutils instead of the micro-ROS fork? We keep aligned with the mainline.

**Comment by robertobucher** [comment]
I don't know exactly the effects of this check

#ifndef __INCLUDE_DIRENT_H

on the other OS (freertos and zephyr).

For NuttX it is required that the type DIR is not redefined, and the definition is in dirent.h!

**Comment by pablogs9** [comment]
Please rebase on top of the target branch

**Comment by robertobucher** [comment]
Hi Pablo

How can I contact the microROS community? I reached to have NuttX 
working again as microROS node with a very little modification in 
rcutils (see my PR)!
There are some problems related to galactic, but I don't know if such 
problems are under solution. For example the provided example for 
Freertos with services (AddTwoInts) is not working under Galactic but it 
is ok under Humble...

Best regards

Roberto

**Comment by pablogs9** [comment]
Hi @robertobucher,

We will appreciate improvements to the micro-ROS module for Nuttx, could you reopen this PR?

Regarding your questions:
- the micro-ROS community is in slack, you can have an invitation here: https://micro.ros.org/ or just write me with your email so I can invite you.
- ROS 2 services do not work between Galactic and micro-ROS due to middleware incompatibility. Galactic by default uses cyclone DDS and its services are not compatible with Fast DDS (micro-ROS' default). On the other hand, Galactic is EOL, so i recommend moving to humble.

**Pull request closed without merging**
