### PR TITLE
Don't link dl library when not needed

### PR DESCRIPTION
**Pull request by bjsowa**

### CODE REVIEW

**Comment by pablogs9** [comment]
Are you building micro-ROS with `RCUTILS_NO_FILESYSTEM` disabled?

**Comment by bjsowa** [comment]
I'm building with `RCUTILS_NO_FILESYSTEM` option enabled.

**Comment by pablogs9** [comment]
In that case you are not linking `target_link_libraries(${PROJECT_NAME} ${CMAKE_DL_LIBS})`

Why do you need this change?

**Comment by bjsowa** [comment]
That's exactly why I need it, so it does not get linked.

**Comment by pablogs9** [comment]
Understood

**Comment by pablogs9** [comment]
@mergify backport iron humble

**Review by pablogs9 — APPROVED** [review]

**Pull request merged**
